[package]
name = "client"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]

[dependencies]
presentrs = { git = "https://github.com/jvff/presentrs", features = ["client"] }
yew = { git = "https://github.com/DenisKolodin/yew" }
