[package]
name = "server"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]

[dependencies]
presentrs = { path = "/tmp/presentrs", features = ["server"] }

[build-dependencies]
presentrs = { path = "/tmp/presentrs", features = ["server"] }
